### ISSUE TITLE
"Fehlbuchung" responsiveness

### ISSUE THREAD

**Issue by Strandtasche** [fsmi/odie-client#53] opened 2015-01-22 11:00 UTC
When in "Abrechnungskorrektur" trying to correct printing costs causes no response: the success or failure of said action should be indicated by a green symbol,  just like after pressing the "print" button in "Auswahl"

**Comment by Kha** [comment] 2015-01-22 11:01
Duplicate of #44

**Closed by Kha** 2015-01-22 11:01 UTC
